spring:
  application:
    name: quality-control-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/factory-realm

server:
  port: 8081

frame-check-result-topic: frame.check.results